# Generated by Django 3.2.8 on 2021-10-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
