# Generated by Django 3.2.8 on 2021-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0002_auto_20211018_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='person',
            name='isVerified',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
