# Generated by Django 3.2.8 on 2021-10-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApi', '0004_rename_name_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
